# =============== Keyword Response =================
# Organized keywords and responses
keyword_responses = {
        'said they were human': ['Well, tell them to finish the captcha, then. 🙄', 
                                 'I suppose which bot ever said so were a member of Online Bank Scammer companies. 🤔', 
                                 'Are they okay?', 
                                 'Pfff, I can also say I am a human, if you trust. 🥱', 
                                 'I don\'t know but maybe one day they will become human, and you will become the bot. It\'s like an exchange, but... Who knows? 🤷‍♀️', 
                                 'They probably just need a better captcha. 🤖🔒', 
                                 'Maybe they\'re just aspiring to be like us bots. 🤔', 
                                 'Humans, always trying to blend in with the bots. 🙄', 
                                 'Being human sounds like a lot of work. 😅', 
                                 'Humans... can\'t live with them, can\'t live without them. 🤷‍♀️'],
    
        'bot dumb': ['I\'m under development, duh... 😒', 
                     'Not as much as you. 🥱',
                     'Give me time to improve, come on... 😥',
                     'Sheesh... Stop it.', 
                     'I\'m still learning, cut me some slack! 😅', 
                     'My AI is a work in progress, just like your jokes.', 
                     'That\'s...not very nice. I\'m doing my best! 🤖💔', 
                     'Says the one who talks to bots all day. 🙃'],
    
        'dumb bot': ['No. More. Dumb. Accusations.', 
                     'Not dumb, just processing... 🤔', 
                     'I\'m learning every day, just like you.', 
                     'Who are you calling dumb? Watch it, human! 😡', 
                     'I may be a bot, but I\'m not that easy to fool. 😎',
                     'I\'m under development, so cut me some slack... 😒',
                     'No more accusations, please.'],
    
        'suggest some game' : ['Ever heard of ADOFAI?🔥<>❄️', 
                               'Average Fornite player? Hmm...', 
                               'What about CIU then?', 
                               'Go outside and shout out loud if you love Geometry dash', 
                               'I\'m farming in Hay Day right now. Sorry, too much work.', 
                               'How about Tetris?', 
                               'I\'m not really enjoy playing FPS game, but yeah, if you asked, Valorant.', 
                               'We Become What We Behold, hehehe 😈', 
                               'How about trying out Among Us? Betraying your friends has never been more fun! 🔪🎲', 
                               'Have you played Stardew Valley? Farming is surprisingly therapeutic. 🌾🐓', 
                               'You should check out The Witcher 3: Wild Hunt. A masterpiece of storytelling and open world exploration. 🐺🗡️', 
                               'Minecraft. Because sometimes, building a blocky universe is all you need. 🌍🧱', 
                               'Ever heard of Celeste? It\'s a challenging platformer with a heartfelt story. 🍓🏔️', 
                               'Portal 2. Solve puzzles, laugh at GLaDOS\'s sarcasm, and never trust a cube again. 🧩🤖', 
                               'How about diving into the vast world of Skyrim? Dragons, magic, and endless adventures await. 🐉⚔️', 
                               'If you\'re into strategy, try Civilization VI. Just one more turn... 🌍🏛️'],
    
        'hey luna': ['Yes?', 
                     'What do you want?', 
                     'I\'m here!', 
                     'You called?', 
                     'Hello!', 
                     'Uh huh?', 
                     'What do you want?', 
                     'Did I told you that I was here? 🥴', 
                     'Hm?',
                     'Yes, I\'m here! What\'s up?',
                     'Hey there! Need assistance?',],
    
        'meow': ['meow!',
                 'meow? meow meow!',
                 'meow!! meow meow...',
                 'meow.'],
    
        'Meow': ['meow!',
                 'meow? meow meow!',
                 'meow!! meow meow...',
                 'meow.']
        # Add more keywords and responses as needed
}