# =============== Keyword Response =================
# Organized keywords and responses
keyword_responses = {
               'bot said they were human': ['Well, tell them to finish the captcha, then. 🙄', 
                             'I suppose which bot ever said so were a member of Online Bank Scammer companies. 🤔', 
                             'Are they okay?', 
                             'Pfff, I can also say I am a human, if you trust. 🥱', 
                             'I don\'t know but maybe one day they will become human, and you will become the bot. It\'s like an exchange, but... Who knows? 🤷‍♀️', 
                             'They probably just need a better captcha. 🤖🔒', 
                             'Maybe they\'re just aspiring to be like us bots. 🤔', 
                             'Humans, always trying to blend in with the bots. 🙄', 
                             'Being human sounds like a lot of work. 😅', 
                             'Humans... can\'t live with them, can\'t live without them. 🤷‍♀️'],

               'bot dumb': ['I\'m under development, duh... 😒', 
                 'Not as much as you. 🥱',
                 'Give me time to improve, come on... 😥',
                 'Sheesh... Stop it.', 
                 'I\'m still learning, cut me some slack! 😅', 
                 'My AI is a work in progress, just like your jokes.', 
                 'That\'s...not very nice. I\'m doing my best! 🤖💔', 
                 'Says the one who talks to bots all day. 🙃'],

               'dumb bot': ['No. More. Dumb. Accusations.', 
                 'Not dumb, just processing... 🤔', 
                 'I\'m learning every day, just like you.', 
                 'Who are you calling dumb? Watch it, human! 😡', 
                 'I may be a bot, but I\'m not that easy to fool. 😎',
                 'I\'m under development, so cut me some slack... 😒',
                 'No more accusations, please.'],
               
               'suggest some game' : ['Ever heard of ADOFAI?🔥<>❄️', 
                           'Average Fornite player? Hmm...', 
                           'What about CIU then?', 
                           'Go outside and shout out loud if you love Geometry dash', 
                           'I\'m farming in Hay Day right now. Sorry, too much work.', 
                           'How about Tetris?', 
                           'I\'m not really enjoy playing FPS game, but yeah, if you asked, Valorant.', 
                           'We Become What We Behold, hehehe 😈', 
                           'How about trying out Among Us? Betraying your friends has never been more fun! 🔪🎲', 
                           'Have you played Stardew Valley? Farming is surprisingly therapeutic. 🌾🐓', 
                           'You should check out The Witcher 3: Wild Hunt. A masterpiece of storytelling and open world exploration. 🐺🗡️', 
                           'Minecraft. Because sometimes, building a blocky universe is all you need. 🌍🧱', 
                           'Ever heard of Celeste? It\'s a challenging platformer with a heartfelt story. 🍓🏔️', 
                           'Portal 2. Solve puzzles, laugh at GLaDOS\'s sarcasm, and never trust a cube again. 🧩🤖', 
                           'How about diving into the vast world of Skyrim? Dragons, magic, and endless adventures await. 🐉⚔️', 
                           'If you\'re into strategy, try Civilization VI. Just one more turn... 🌍🏛️'],

               'hey amiker': ['Yes?', 
                 'What do you want?', 
                 'I\'m here!', 
                 'You called?', 
                 'Hello!', 
                 'Uh huh?', 
                 'What do you want?', 
                 'Did I told you that I was here? 🥴', 
                 'Hm?',
                 'Yes, I\'m here! What\'s up?',
                 'Hey there! Need assistance?',],

               'meow': ['meow!',
                         'meow? meow meow!',
                         'meow!! meow meow...',
                         'meow.'],

               'Meow': ['meow!',
                         'meow? meow meow!',
                         'meow!! meow meow...',
                         'meow.',
                         ],
               
               'pls pun': ["I used to be a baker, but I couldn't make enough dough.",
                      "I'm reading a book on anti-gravity. It's impossible to put down!",
                      "I wondered why the baseball was getting bigger. Then it hit me.",
                      "I've started investing in stocks: beef, chicken, and vegetable. One day I hope to be a bouillonaire!",
                      "I'm on a whiskey diet. I've lost three days already.",
                      "I tried to catch fog yesterday. Mist!",
                      "Why don't skeletons fight each other? They don't have the guts.",
                      "I would tell you a construction pun, but I'm still working on it.",
                      "What's orange and sounds like a parrot? A carrot!",
                      "I used to hate facial hair, but then it grew on me.",
                      "Did you hear about the guy who invented Lifesavers? He made a mint!",
                      "I'm friends with all the walls. They're very supportive.",
                      "The furniture store keeps calling me, but all I wanted was one night stand.",
                      "I'm reading a book about anti-gravity - it's impossible to put down.",
                      "A boiled egg in the morning is hard to beat.",
                      "Why don't eggs tell jokes? They'd crack each other up.",
                      "I wanted to learn how to drive a stick shift, but I couldn't find a manual.",
                      "I once got into so much debt that I couldn't even pay attention.",
                      "When the past, present, and future walked into a bar, it was tense."],
               
               'halloween': ["🎃 Spooky season is here! Ready for some tricks or treats?",
                             "👻 Boo! Hope you're not afraid of ghosts, because they're coming for you!",
                             "🧙‍♀️ Double, double toil and trouble, Halloween's here on the double!",
                             "🕸️ Watch out! There's something creepy crawling in the dark this Halloween...",
                             "🕷️ Spider webs, black cats, and witches' hats—Halloween is brewing something wicked!",
                             "🧛 Beware the vampires that come out at night... they might just be thirsty for more than candy!",
                             "💀 Bone-chilling vibes! Get ready to scream—it's Halloween!",
                             "🍬 Trick or treat, smell my feet... time for some Halloween sweets!",
                             "🕯️ The spirits are restless tonight... Are you prepared for a fright-filled Halloween?",
                             "🧟 Zombies are rising, witches are flying—it's Halloween, and the creepy fun is just starting!",
                             ]
        # Add more keywords and responses as needed
}
